# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ginv_cpp <- function(initialized_matrix, tol = 1e-6) {
    .Call(`_SigBridgeRUtils_ginv_cpp`, initialized_matrix, tol)
}

normalize_quantiles_cpp <- function(initialized_matrix) {
    .Call(`_SigBridgeRUtils_normalize_quantiles_cpp`, initialized_matrix)
}

