# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

normalize_quantiles_dense <- function(x, copy = TRUE, keep_names = FALSE) {
    .Call('_SigBridgeRUtils_normalize_quantiles_dense', PACKAGE = 'SigBridgeRUtils', x, copy, keep_names)
}

normalize_quantiles_sparse <- function(x, copy = TRUE, keep_names = FALSE) {
    .Call('_SigBridgeRUtils_normalize_quantiles_sparse', PACKAGE = 'SigBridgeRUtils', x, copy, keep_names)
}

normalize_quantiles_cpp <- function(x, copy = TRUE, keep_names = FALSE) {
    .Call('_SigBridgeRUtils_normalize_quantiles_cpp', PACKAGE = 'SigBridgeRUtils', x, copy, keep_names)
}

